# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Liwei Kang's Homepage 
email: kangliwei98@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Hi, I am Liwei Kang, an undergraduate student in Shanghai Jiao Tong University, majoring in Computer Science.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://kanglw.com" # the base hostname & protocol for your site
# twitter_username: jekyllrb
github_username:  Olafyii

# Build settings
markdown: kramdown

# remote_theme: thelehhman/texture

permalink: /:categories/:title/
theme: jekyll-theme-cayman